import asyncio
import logging
import os
import pathlib
import sys
from datetime import datetime, timezone
from typing import List, Optional
from uuid import UUID

from fastapi import HTTPException
from sqlalchemy.orm.exc import StaleDataError
from sqlmodel import Session, col, select

from src.services.producers.base_event_handler import EventType

from src.services.enrichments_bl import EnrichmentsBl
from src.repositories.db import (
    add_alerts_to_incident,
    add_audit,
    create_incident_from_dto,
    delete_incident_by_id,
    enrich_alerts_with_incidents,
    get_all_alerts_by_fingerprints,
    get_incident_by_id,
    get_incident_unique_fingerprint_count,
    is_all_alerts_resolved,
    is_first_incident_alert_resolved,
    is_last_incident_alert_resolved,
    remove_alerts_to_incident_by_incident_id,
    update_incident_from_dto_by_id,
    update_incident_severity,
)
from src.repositories.elastic import ElasticClient
from src.repositories.incidents import get_last_incidents_by_cel
from src.models.action_type import ActionType
from src.models.alert import AlertStatus
from src.models.db.alert import Alert, LastAlert
from src.models.db.incident import (
    Incident,
    IncidentDismissMode,
    IncidentSeverity,
    IncidentStatus,
)
from src.models.db.rule import ResolveOn
from src.models.incident import (
    IncidentDto,
    IncidentDtoIn,
    IncidentSorting,
    IncidentStatusChangeDto,
)
from src.utils.enrichment_helpers import convert_db_alerts_to_dto_alerts
from src.utils.pagination import IncidentsPaginatedResultsDto
from src.services.identity_manager.authenticatedentity import AuthenticatedEntity
from src.services.sse import notify_sse


MIN_INCIDENT_ALERTS_FOR_SUMMARY_GENERATION = int(
    os.environ.get("MIN_INCIDENT_ALERTS_FOR_SUMMARY_GENERATION", 5)
)

ee_enabled = os.environ.get("EE_ENABLED", "false") == "true"
if ee_enabled:
    path_with_ee = (
        str(pathlib.Path(__file__).parent.resolve()) + "/../../../ee/experimental"
    )
    sys.path.insert(0, path_with_ee)
else:
    ALGORITHM_VERBOSE_NAME = NotImplemented


class IncidentBl:
    def __init__(
        self,
        tenant_id: str,
        session: Session,
        user: str = None,
    ):
        self.tenant_id = tenant_id
        self.user = user
        self.session = session
        self.logger = logging.getLogger(__name__)
        self.ee_enabled = os.environ.get("EE_ENABLED", "false").lower() == "true"
        self.redis = os.environ.get("REDIS", "false") == "true"

    def create_incident(
        self,
        incident_dto: [IncidentDtoIn | IncidentDto],
        generated_from_ai: bool = False,
    ) -> IncidentDto:
        """
        Creates a new incident.

        Args:
            incident_dto (IncidentDtoIn | IncidentDto): The data transfer object containing the details of the incident to be created.
            generated_from_ai (bool, optional): Indicates if the incident was generated by Keep's AI. Defaults to False.

        Returns:
            IncidentDto: The newly created incident object, containing details of the incident.
        """
        self.logger.info(
            "Creating incident",
            extra={"incident_dto": incident_dto.dict(), "tenant_id": self.tenant_id},
        )
        incident = create_incident_from_dto(
            self.tenant_id,
            incident_dto,
            generated_from_ai=generated_from_ai,
            session=self.session,
        )
        self.logger.info(
            "Incident created",
            extra={"incident_id": incident.id, "tenant_id": self.tenant_id},
        )
        new_incident_dto = IncidentDto.from_db_incident(incident)
        self.logger.info(
            "Incident DTO created",
            extra={"incident_id": new_incident_dto.id, "tenant_id": self.tenant_id},
        )
        self.update_client_on_incident_change()
        self.logger.info(
            "Client updated on incident change",
            extra={"incident_id": new_incident_dto.id, "tenant_id": self.tenant_id},
        )

        return new_incident_dto

    def sync_add_alerts_to_incident(self, *args, **kwargs) -> None:
        """
        Synchronous wrapper for the async add_alerts_to_incident method.
        """
        asyncio.run(self.add_alerts_to_incident(*args, **kwargs))

    async def add_alerts_to_incident(
        self,
        incident_id: UUID,
        alert_fingerprints: List[str],
        is_created_by_ai: bool = False,
        override_count: bool = False,
        change_by: Optional[AuthenticatedEntity] = None,
        enrichment_bl: Optional[EnrichmentsBl] = None,
    ) -> None:
        self.logger.info(
            "Adding alerts to incident",
            extra={
                "incident_id": incident_id,
                "alert_fingerprints": alert_fingerprints,
            },
        )
        incident = get_incident_by_id(
            tenant_id=self.tenant_id, incident_id=incident_id, session=self.session
        )
        if not incident:
            raise HTTPException(status_code=404, detail="Incident not found")

        add_alerts_to_incident(
            self.tenant_id,
            incident,
            alert_fingerprints,
            is_created_by_ai,
            session=self.session,
            override_count=override_count,
        )
        self.logger.info(
            "Alerts added to incident",
            extra={
                "incident_id": incident_id,
                "alert_fingerprints": alert_fingerprints,
            },
        )
        await self.inherit_incident_status(
            incident,
            alert_fingerprints,
            change_by=change_by,
            enrichment_bl=enrichment_bl,
        )
        self.__postprocess_alerts_change(incident, alert_fingerprints)
        self.logger.info(
            "Alerts added and postprocessed for incident",
            extra={
                "incident_id": incident_id,
                "alert_fingerprints": alert_fingerprints,
            },
        )

    def __update_elastic(self, alert_fingerprints: List[str]):
        try:
            elastic_client = ElasticClient(self.tenant_id)
            if elastic_client.enabled:
                db_alerts = get_all_alerts_by_fingerprints(
                    tenant_id=self.tenant_id,
                    fingerprints=alert_fingerprints,
                    session=self.session,
                )
                db_alerts = enrich_alerts_with_incidents(
                    self.tenant_id, db_alerts, session=self.session
                )
                enriched_alerts_dto = convert_db_alerts_to_dto_alerts(
                    db_alerts, with_incidents=True
                )
                elastic_client.index_alerts(alerts=enriched_alerts_dto)
        except Exception:
            self.logger.exception("Failed to push alert to elasticsearch")
            raise

    def update_client_on_incident_change(self, incident_id: Optional[UUID] = None):
        self.logger.info(
            "Pushing incident change to client",
            extra={"incident_id": incident_id, "tenant_id": self.tenant_id},
        )
        try:
            notify_sse(
                self.tenant_id,
                "incident-change",
                {"incident_id": str(incident_id) if incident_id else None},
            )
            self.logger.info(
                "Incident change pushed to client",
                extra={"incident_id": incident_id, "tenant_id": self.tenant_id},
            )
        except Exception:
            self.logger.exception(
                "Failed to push incident change to client",
                extra={"incident_id": incident_id, "tenant_id": self.tenant_id},
            )



    def delete_alerts_from_incident(
        self, incident_id: UUID, alert_fingerprints: List[str]
    ) -> None:
        self.logger.info(
            "Fetching incident",
            extra={
                "incident_id": incident_id,
                "tenant_id": self.tenant_id,
            },
        )
        incident = get_incident_by_id(tenant_id=self.tenant_id, incident_id=incident_id)
        if not incident:
            raise HTTPException(status_code=404, detail="Incident not found")

        remove_alerts_to_incident_by_incident_id(
            self.tenant_id, incident_id, alert_fingerprints
        )
        self.__postprocess_alerts_change(incident, alert_fingerprints)

    def delete_incident(self, incident_id: UUID) -> None:
        self.logger.info(
            "Fetching incident",
            extra={
                "incident_id": incident_id,
                "tenant_id": self.tenant_id,
            },
        )

        incident = get_incident_by_id(tenant_id=self.tenant_id, incident_id=incident_id)
        if not incident:
            raise HTTPException(status_code=404, detail="Incident not found")

        incident_dto = IncidentDto.from_db_incident(incident)

        deleted = delete_incident_by_id(
            tenant_id=self.tenant_id, incident_id=incident_id
        )
        if not deleted:
            raise HTTPException(status_code=404, detail="Incident not found")

        self.update_client_on_incident_change()

    def bulk_delete_incidents(self, incident_ids: List[UUID]) -> None:
        for incident_id in incident_ids:
            self.delete_incident(incident_id)

    def update_incident(
        self,
        incident_id: UUID,
        updated_incident_dto: IncidentDtoIn,
        generated_by_ai: bool,
    ) -> IncidentDto:
        self.logger.info(
            "Fetching incident",
            extra={
                "incident_id": incident_id,
                "tenant_id": self.tenant_id,
            },
        )
        incident = update_incident_from_dto_by_id(
            self.tenant_id, incident_id, updated_incident_dto, generated_by_ai
        )
        return self.__postprocess_incident_change(incident)

    def __postprocess_alerts_change(self, incident, alert_fingerprints):
        self.__update_elastic(alert_fingerprints)
        self.logger.info(
            "Alerts pushed to elastic",
            extra={
                "incident_id": incident.id,
                "alert_fingerprints": alert_fingerprints,
            },
        )
        self.update_client_on_incident_change(incident.id)
        self.logger.info(
            "Client updated on incident change",
            extra={
                "incident_id": incident.id,
                "alert_fingerprints": alert_fingerprints,
            },
        )
        incident_dto = IncidentDto.from_db_incident(incident)



    def update_severity(
        self,
        incident_id: UUID,
        severity: IncidentSeverity,
        comment: Optional[str] = None,
    ) -> IncidentDto:
        self.logger.info(
            "Fetching incident",
            extra={
                "incident_id": incident_id,
                "tenant_id": self.tenant_id,
            },
        )
        incident = update_incident_severity(
            self.tenant_id,
            incident_id,
            severity,
        )

        if comment:
            add_audit(
                self.tenant_id,
                str(incident_id),
                self.user,
                ActionType.INCIDENT_COMMENT,
                comment,
            )

        return self.__postprocess_incident_change(incident)

    def __postprocess_incident_change(self, incident):
        if not incident:
            raise HTTPException(status_code=404, detail="Incident not found")

        new_incident_dto = IncidentDto.from_db_incident(incident)

        self.update_client_on_incident_change(incident.id)
        self.logger.info(
            "Client updated on incident change",
            extra={"incident_id": incident.id},
        )


        return new_incident_dto

    @staticmethod
    def query_incidents(
        tenant_id: str,
        limit: int = 25,
        offset: int = 0,
        timeframe: int = None,
        upper_timestamp: datetime = None,
        lower_timestamp: datetime = None,
        is_candidate: bool = False,
        sorting: Optional[IncidentSorting] = IncidentSorting.creation_time,
        with_alerts: bool = False,
        is_predicted: bool = None,
        cel: str = None,
        allowed_incident_ids: Optional[List[str]] = None,
    ):
        incidents, total_count = get_last_incidents_by_cel(
            tenant_id=tenant_id,
            limit=limit,
            offset=offset,
            timeframe=timeframe,
            upper_timestamp=upper_timestamp,
            lower_timestamp=lower_timestamp,
            is_candidate=is_candidate,
            sorting=sorting,
            with_alerts=with_alerts,
            is_predicted=is_predicted,
            cel=cel,
            allowed_incident_ids=allowed_incident_ids,
        )
        incidents_dto = []
        for incident in incidents:
            incidents_dto.append(IncidentDto.from_db_incident(incident))

        return IncidentsPaginatedResultsDto(
            limit=limit, offset=offset, count=total_count, items=incidents_dto
        )

    def resolve_incident_if_require(
        self, incident: Incident, max_retries=3
    ) -> Incident:
        should_resolve = False

        if incident.resolve_on == ResolveOn.ALL.value and is_all_alerts_resolved(
            incident=incident, session=self.session
        ):
            should_resolve = True

        elif (
            incident.resolve_on == ResolveOn.FIRST.value
            and is_first_incident_alert_resolved(incident, session=self.session)
        ):
            should_resolve = True

        elif (
            incident.resolve_on == ResolveOn.LAST.value
            and is_last_incident_alert_resolved(incident, session=self.session)
        ):
            should_resolve = True

        incident_id = incident.id

        if should_resolve:
            for attempt in range(max_retries):
                try:
                    incident.status = IncidentStatus.RESOLVED.value
                    self.session.add(incident)
                    self.session.commit()
                    break
                except StaleDataError as ex:
                    if "expected to update" in ex.args[0]:
                        self.logger.info(
                            f"Phantom read detected while updating incident `{incident_id}`, retry #{attempt}"
                        )
                        self.session.rollback()
                        continue

        return incident

    async def change_status(
        self,
        incident_id: UUID | str,
        new_status: IncidentStatus,
        change_by: AuthenticatedEntity,
        dispose_on_new_alert: bool = False,
        dismiss_mode: Optional[IncidentDismissMode] = None,
        dismissed_until: Optional[datetime] = None,
        commit: bool = True,
        enrichment_bl: Optional[EnrichmentsBl] = None,
    ) -> IncidentDto:
        """Move an incident to `new_status`, carrying its alerts along.

        SUPPRESSED is the odd one out: it is never written to `incident.status`,
        because a time-boxed dismissal has to be able to lapse without anything
        rewriting the row. It is recorded as dismiss state instead, layered over
        the status the incident reverts to. Every other status change clears
        that dismiss state — asking for firing/acknowledged/resolved is an
        explicit statement that the incident should be visible again.

        The alerts follow per `_status_to_propagate`; see that docstring for which
        transitions reach them.

        `commit=False` stages the change and skips the client notification, for
        callers bundling it into a larger transaction. They own the commit and
        must notify afterwards.
        """
        self.logger.info(
            "Fetching incident",
            extra={
                "incident_id": incident_id,
                "tenant_id": self.tenant_id,
            },
        )

        # Alerts are needed whenever the change might reach them, which is every
        # status except resolved.
        incident = get_incident_by_id(
            self.tenant_id, incident_id, with_alerts=True, session=self.session
        )

        if not incident:
            raise HTTPException(status_code=404, detail="Incident not found")

        previous_status = incident.get_effective_status()

        if new_status == IncidentStatus.RESOLVED:
            end_time = datetime.now(tz=timezone.utc)
            incident.end_time = end_time

        if incident.assignee != change_by.email:
            incident.assignee = change_by.email
            add_audit(
                self.tenant_id,
                str(incident_id),
                change_by.email,
                ActionType.INCIDENT_ASSIGN,
                f"Incident self-assigned to {change_by.email}",
                session=self.session,
                commit=False,
            )

        if new_status == IncidentStatus.SUPPRESSED:
            # Leave `incident.status` untouched — it is what the incident shows
            # again once the dismissal lifts.
            incident.dismiss_mode = (
                dismiss_mode or IncidentDismissMode.PERMANENT
            ).value
            incident.dismissed_until = (
                dismissed_until
                if incident.dismiss_mode == IncidentDismissMode.DISMISS_UNTIL.value
                else None
            )
            if incident.dismissed_until is not None:
                audit_description = (
                    f"Incident suppressed until {incident.dismissed_until.isoformat()}"
                )
            else:
                audit_description = "Incident suppressed permanently"
        else:
            incident.dismiss_mode = None
            incident.dismissed_until = None
            incident.status = new_status.value
            audit_description = (
                f"Incident status changed from {previous_status} to {new_status.value}"
            )

        add_audit(
            self.tenant_id,
            str(incident_id),
            change_by.email,
            ActionType.INCIDENT_STATUS_CHANGE,
            audit_description,
            session=self.session,
            commit=False,
        )
        self.session.add(incident)

        # Acknowledging is claiming: whoever the incident is now assigned to is
        # assigned its alerts too. This is a property of the transition, not of
        # the endpoint — it applies equally to the status modal and to
        # self-assign, which reaches this method as an acknowledge.
        assignee = (
            incident.assignee
            if new_status == IncidentStatus.ACKNOWLEDGED
            else None
        )

        await self.propagate_status_to_alerts(
            incident,
            previous_status=previous_status,
            new_status=new_status,
            change_by=change_by,
            dispose_on_new_alert=dispose_on_new_alert,
            enrichment_bl=enrichment_bl,
            assignee=assignee,
        )

        if not commit:
            self.session.flush()
            return IncidentDto.from_db_incident(incident)

        self.session.commit()

        return self.__postprocess_incident_change(incident)

    @staticmethod
    def _status_to_propagate(
        previous_status: str, new_status: IncidentStatus
    ) -> Optional[IncidentStatus]:
        """Which status the incident's alerts should take on, or None to leave
        them alone.

          -> suppressed / acknowledged : always propagates. The incident is being
             quietened or claimed, and its alerts should say so too.
          -> firing, from suppressed or acknowledged : propagates. Whatever
             propagation put the alerts there is undone the same way, so they
             never sit in a status the incident no longer holds.
          -> firing, from firing : nothing to do.
          -> resolved : never propagates. Resolving an incident is a statement
             about the incident, not a claim that each underlying alert has
             stopped firing.
        """
        if new_status in (IncidentStatus.SUPPRESSED, IncidentStatus.ACKNOWLEDGED):
            return new_status
        if new_status == IncidentStatus.FIRING and previous_status in (
            IncidentStatus.SUPPRESSED.value,
            IncidentStatus.ACKNOWLEDGED.value,
        ):
            return IncidentStatus.FIRING
        return None

    async def propagate_status_to_alerts(
        self,
        incident: Incident,
        previous_status: str,
        new_status: IncidentStatus,
        change_by: AuthenticatedEntity,
        dispose_on_new_alert: bool = False,
        enrichment_bl: Optional[EnrichmentsBl] = None,
        fingerprints: Optional[List[str]] = None,
        assignee: Optional[str] = None,
        commit: bool = False,
    ) -> List[str]:
        """Push the incident's status onto its non-resolved alerts.

        Resolved alerts are never touched: an alert that has stopped firing has
        finished its own lifecycle, and dragging it back out would misreport
        reality. Everything else — firing, acknowledged, already suppressed —
        takes the incident's status.

        Suppression is expressed as dismiss state, NOT as status='suppressed':
        alerts derive suppression from dismiss_mode/dismissed_until the same way
        incidents do, so copying the incident's deadline is what makes the alert
        come back on the same clock. Writing a status would strand it suppressed.

        Returns the fingerprints actually written, for logging and tests.

        `commit=False` (the default) stages the writes for a caller that owns the
        transaction — `change_status` commits the incident and its alerts
        together. `commit=True` is for callers with no wider transaction to join;
        it commits, then announces the batch, in that order.
        """
        target = self._status_to_propagate(previous_status, new_status)
        if target is None and assignee is None:
            return []

        candidates = (
            fingerprints
            if fingerprints is not None
            else [alert.fingerprint for alert in incident.alerts]
        )
        if not candidates:
            return []

        affected = self._non_resolved_fingerprints(candidates)
        if not affected:
            return []

        enrichments: dict = {}
        if target == IncidentStatus.SUPPRESSED:
            # Mirror the incident's dismissal, deadline included, and leave the
            # alerts' own status override alone — that is what they revert to.
            enrichments["dismiss_mode"] = incident.dismiss_mode
            enrichments["dismissed_until"] = incident.dismissed_until
        elif target is not None:
            # Acknowledged/firing are plain statuses, and they end any dismissal
            # the alert was under — it is visible again by definition.
            enrichments["status"] = target.value
            enrichments["dismiss_mode"] = None
            enrichments["dismissed_until"] = None

        if assignee is not None:
            enrichments["assignee"] = assignee

        bl = enrichment_bl or EnrichmentsBl(self.tenant_id, db=self.session)
        action_type, action_description, _ = bl.get_enrichment_metadata(
            enrichments, change_by
        )
        action_description = (
            f"{action_description} (propagated from incident {incident.id})"
        )

        self.logger.info(
            "Propagating incident status to alerts",
            extra={
                "incident_id": str(incident.id),
                "tenant_id": self.tenant_id,
                "target_status": target.value if target else None,
                "alerts": len(affected),
                "skipped_resolved": len(candidates) - len(affected),
            },
        )

        await bl.batch_enrich(
            affected,
            enrichments,
            action_type,
            change_by.email,
            action_description,
            dispose_on_new_alert=dispose_on_new_alert,
            # Never announce from in here: the rows are not durable yet, whether
            # the commit below is ours or the caller's.
            produce_event=False,
            commit=False,
        )

        if commit:
            self.session.commit()
            if bl.event_producer is not None:
                await bl.publish_enrichment_event(
                    fingerprint=affected,
                    enrichments=enrichments,
                    action_type=action_type,
                    action_callee=change_by.email,
                    action_description=action_description,
                    event_type=EventType.BATCH_ENRICH,
                )

        return affected

    async def inherit_incident_status(
        self,
        incident: Incident,
        alert_fingerprints: List[str],
        change_by: Optional[AuthenticatedEntity] = None,
        enrichment_bl: Optional[EnrichmentsBl] = None,
    ) -> List[str]:
        """Apply a suppressed/acknowledged incident's state to alerts that have
        just been linked to it.

        Without this, dismissing an incident only quietens the alerts it held at
        that moment — the next alert to correlate in would light it up again,
        which defeats the point of dismissing it. A time-boxed dismissal is
        inherited deadline and all, so the new alert comes back on the same clock
        as the incident.

        Only suppressed and acknowledged are inherited; a firing or resolved
        incident has nothing to impose on an alert that just arrived.
        """
        effective = incident.get_effective_status()
        if effective not in (
            IncidentStatus.SUPPRESSED.value,
            IncidentStatus.ACKNOWLEDGED.value,
        ):
            return []

        actor = change_by or AuthenticatedEntity(
            tenant_id=self.tenant_id,
            email=self.user or "keep",
        )
        # `previous_status` is FIRING so the transition reads as "entering" the
        # incident's current state, which is what propagation keys off.
        #
        # commit=True: linking alerts is its own operation, already committed by
        # `add_alerts_to_incident` above, so there is no wider transaction for
        # these writes to join. Without it they would be staged and then dropped
        # when the session closes.
        return await self.propagate_status_to_alerts(
            incident,
            previous_status=IncidentStatus.FIRING.value,
            new_status=IncidentStatus(effective),
            change_by=actor,
            enrichment_bl=enrichment_bl,
            fingerprints=alert_fingerprints,
            commit=True,
        )

    def _non_resolved_fingerprints(self, fingerprints: List[str]) -> List[str]:
        """Filter to the alerts that are not resolved, by EFFECTIVE status — the
        user's override, or the provider's value when there is none. Reading
        `alert.status` alone would re-suppress an alert a user had resolved by
        hand; reading `lastalert.status` alone would miss provider resolutions."""
        if not fingerprints:
            return []

        rows = self.session.exec(
            select(LastAlert, Alert.status)
            .join(Alert, LastAlert.alert_id == Alert.id)
            .where(
                LastAlert.tenant_id == self.tenant_id,
                col(LastAlert.fingerprint).in_(fingerprints),
            )
        ).all()

        keep = []
        for last_alert, provider_status in rows:
            effective = last_alert.get_effective_status(provider_status)
            if effective != AlertStatus.RESOLVED.value:
                keep.append(last_alert.fingerprint)
        return keep

    async def enrich_and_change_status(
        self,
        incident_id: UUID | str,
        change: Optional[IncidentStatusChangeDto],
        enrichments: Optional[dict],
        change_by: AuthenticatedEntity,
        enrichment_bl: EnrichmentsBl,
        force: bool = False,
    ) -> IncidentDto:
        """Apply an enrichment and a status change to one incident atomically.

        These arrive together — dismissing an incident in the UI is a status
        change plus a note — and splitting them across two requests meant a
        failure could leave the note saved with the dismissal missing, with
        nothing to say which half landed. Both writes are staged on one session
        and committed once; either both apply or neither does.

        Side effects (Kafka, client notification) deliberately run AFTER the
        commit, so nothing downstream is told about a change that may roll back.
        """
        if change is None and not enrichments:
            raise HTTPException(
                status_code=422, detail="Nothing to apply: no enrichments, no status"
            )

        incident_dto = None

        if enrichments:
            await enrichment_bl.enrich_entity(
                fingerprint=incident_id,
                enrichments=enrichments,
                action_type=ActionType.INCIDENT_ENRICH,
                action_callee=change_by.email,
                action_description=f"Incident enriched by {change_by.email}",
                force=force,
                entity_type="incident",
                commit=False,
            )

        if change is not None:
            incident_dto = await self.change_status(
                incident_id,
                change.status,
                change_by,
                change.dispose_on_new_alert,
                dismiss_mode=change.dismiss_mode,
                dismissed_until=change.dismissed_until,
                commit=False,
                enrichment_bl=enrichment_bl,
            )

        self.session.commit()

        # Durable now — safe to tell the rest of the world.
        if enrichments:
            await enrichment_bl.publish_enrichment_event(
                fingerprint=incident_id,
                enrichments=enrichments,
                action_type=ActionType.INCIDENT_ENRICH,
                action_callee=change_by.email,
                action_description=f"Incident enriched by {change_by.email}",
                force=force,
            )

        self.update_client_on_incident_change(
            incident_id if isinstance(incident_id, UUID) else None
        )

        # Re-read rather than returning the DTO built mid-transaction: that one
        # predates the committed enrichment row, so its `enrichments` overlay
        # would be stale.
        incident = get_incident_by_id(
            self.tenant_id, incident_id, session=self.session
        )
        if not incident:
            raise HTTPException(status_code=404, detail="Incident not found")
        return IncidentDto.from_db_incident(incident)